export type CreateBusinessRequest = {
    businessAddressCountry: string,
    businessAddressPostalCode: string,
    businessAddressStreetName: string,
    businessAddressState: string,
    businessAddressLg: string,
    businessAnnualTurnover: string,
    businessCityName: string,
    businessCustomSettings: string,
    businessDescription: string,
    businessEntityId: number,
    businessErpSystem: string,
    businessFirsId: string,
    businessIrnTemplate: string,
    businessNotificationChannels: string,
    businessPartyName: string,
    businessReference: string,
    businessSector: string,
    businessSupportPeppol: boolean,
    businessTelephone: string,
    businessTin: string
}

export const createBusinessRequestInit: CreateBusinessRequest = {
    businessAddressCountry: "",
    businessAddressPostalCode: "",
    businessAddressStreetName: "",
    businessAddressState: "",
    businessAddressLg: "",
    businessAnnualTurnover: "",
    businessCityName: "",
    businessCustomSettings: "",
    businessDescription: "",
    businessEntityId: 0,
    businessErpSystem: "",
    businessFirsId: "",
    businessIrnTemplate: "",
    businessNotificationChannels: "",
    businessPartyName: "",
    businessReference: "",
    businessSector: "",
    businessSupportPeppol: false,
    businessTelephone: "",
    businessTin: ""
}
